### ISSUE TITLE
feature request grid 3 columns

### ISSUE THREAD

**Issue by paulle** [amirzaidi/Shade#10]
Thank you for the nice launcher. I like it, even more because it's open source.
Can you make it possible to choose a grid size with 3 columns and to choose the icon size.
This would be very useful for all people with bad eyes, because most of them prefer to scroll a little more and having a better sight.
Thank you

P.S. Do you think about to put your launcher on f-droid too one day?

**Comment by amirzaidi** [comment]
I'm reworking the grid selection to be a -1 or +1 selection instead of a hardcoded 4/5/6.

> P.S. Do you think about to put your launcher on f-droid too one day?

Maybe, someone uploaded it for DNG Processor, if it was effortless I'd do it but I'd rather spend my time programming than worrying about publishing

**Comment by paulle** [comment]
A -/+ selection would be fine too, because this way is a grid selection for every users choice.

**Comment by amirzaidi** [comment]
In the new update, if you set the device DPI to its highest and enable sparse grid it should go into a 3-column mode.

**Comment by paulle** [comment]
Thank you.
