### ISSUE TITLE
I want to know the function of the plugin.Is like the google feed page?How can I make a custmoize plugin for this launcher ?

### ISSUE THREAD

**Issue by leanderli** [amirzaidi/Shade#12]

**Comment by amirzaidi** [comment]
I realize that I should've written more documentation for this.. I'll do my best to explain.

https://github.com/amirzaidi/Shade/tree/dev/shade/src/com/android/launcher3/plugin

This is a Launcher3 extension that any launcher can import to support the plugins that they would like to support. Plugins all follow a common template:

https://github.com/amirzaidi/StoreShortcut/blob/master/app/src/main/AndroidManifest.xml#L11

You declare a service with intent filter on action com.android.launcher3.PLUGIN. The interface.descriptor and interface.version are used by the launcher to check if the launcher supports the interface of the service.

Shade currently supports these:

https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/activity/ActivityPluginClient.java#L10

An interface that can hook into launcher opening and closing events, used by Pixel Bridge to check for updates.

https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/button/ButtonPluginClient.java#L12

An interface to respond to home button presses, used by Assist Mapper to open an app when the home button is pressed.

https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/shortcuts/ShortcutPluginClient.java#L16

An interface to add custom shortcuts to apps on long press, like Sesame does in Lawnchair. Used by StoreShortcut (the example plugin I linked above) to add "Open in Store" and "Share" shortcuts to apps. It is also used to backport app shortcuts to older Android versions (7.0 and lower).

https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/unread/UnreadPluginClient.java#L14

An interface to override the top text widget behaviour. By default the top text widget does nothing, but this interface is used by Smart Unread to work. Smart Unread is actually quite modular, and is running as an internal plugin in the launcher itself.

If you want to request additional plugin interfaces, make an AIDL interface draft and I will include it in the next update.

The Google Feed page is completely separate from the plugin system. If you want to make a Google Feed alternative, take a look at what Librechair is doing. I have some work in progress code from @paphonb on my PC that might help too: https://hastebin.com/locifaxizu.patch

You can start by creating a service with the com.android.launcher3.WINDOW_OVERLAY action intent filter, that will let Shade recognize it as a valid Feed provider and show it in the settings menu.

If you have more questions, feel free to ask.

**Comment by leanderli** [comment]
> I realize that I should've written more documentation for this.. I'll do my best to explain.
> 
> https://github.com/amirzaidi/Shade/tree/dev/shade/src/com/android/launcher3/plugin
> 
> This is a Launcher3 extension that any launcher can import to support the plugins that they would like to support. Plugins all follow a common template:
> 
> https://github.com/amirzaidi/StoreShortcut/blob/master/app/src/main/AndroidManifest.xml#L11
> 
> You declare a service with intent filter on action com.android.launcher3.PLUGIN. The interface.descriptor and interface.version are used by the launcher to check if the launcher supports the interface of the service.
> 
> Shade currently supports these:
> 
> https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/activity/ActivityPluginClient.java#L10
> 
> An interface that can hook into launcher opening and closing events, used by Pixel Bridge to check for updates.
> 
> https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/button/ButtonPluginClient.java#L12
> 
> An interface to respond to home button presses, used by Assist Mapper to open an app when the home button is pressed.
> 
> https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/shortcuts/ShortcutPluginClient.java#L16
> 
> An interface to add custom shortcuts to apps on long press, like Sesame does in Lawnchair. Used by StoreShortcut (the example plugin I linked above) to add "Open in Store" and "Share" shortcuts to apps. It is also used to backport app shortcuts to older Android versions (7.0 and lower).
> 
> https://github.com/amirzaidi/Shade/blob/dev/shade/src/com/android/launcher3/plugin/unread/UnreadPluginClient.java#L14
> 
> An interface to override the top text widget behaviour. By default the top text widget does nothing, but this interface is used by Smart Unread to work. Smart Unread is actually quite modular, and is running as an internal plugin in the launcher itself.
> 
> If you want to request additional plugin interfaces, make an AIDL interface draft and I will include it in the next update.
> 
> The Google Feed page is completely separate from the plugin system. If you want to make a Google Feed alternative, take a look at what Librechair is doing. I have some work in progress code from @paphonb on my PC that might help too: https://hastebin.com/locifaxizu.patch
> 
> You can start by creating a service with the com.android.launcher3.WINDOW_OVERLAY action intent filter, that will let Shade recognize it as a valid Feed provider and show it in the settings menu.
> 
> If you have more questions, feel free to ask.

Thank you very much.I'll read this document and try to do somthing with it.
