### ISSUE TITLE
widgets panel immediately disappear 

### ISSUE THREAD

**Issue by rchamara** [amirzaidi/Shade#17]
when I open the widget panel, the widget panel immediately disappears and replaces it with a white screen.

Test in: Nexsus 5x API 29 andriod 10

Note: 

set  
sheet.mIsOpen = false; in WidgetFullSheet showing all widgets but can not close widget panel using home button.

```
    public static WidgetsFullSheet show(Launcher launcher, boolean animate) {
        WidgetsFullSheet sheet = (WidgetsFullSheet) launcher.getLayoutInflater()
                .inflate(R.layout.widgets_full_sheet, launcher.getDragLayer(), false);
        sheet.mIsOpen = false;
        launcher.getDragLayer().addView(sheet);
        sheet.open(animate);
        return sheet;
    }
```

screen shots:
![Screenshot_1572579913](https://user-images.githubusercontent.com/23213530/68001019-55fe6d00-fc88-11e9-89ac-702b14d1be86.png)

![Screenshot_1572579945](https://user-images.githubusercontent.com/23213530/68001040-6282c580-fc88-11e9-9307-dedd9efbc3d2.png)

**Comment by H4NG-MAN** [comment]
> when I open the widget panel, the widget panel immediately disappears and replaces it with a white screen.
> 
> Test in: Nexsus 5x API 29 andriod 10
> 
> Note:
> 
> set
> sheet.mIsOpen = false; in WidgetFullSheet showing all widgets but can not close widget panel using home button.
> 
> ```
>     public static WidgetsFullSheet show(Launcher launcher, boolean animate) {
>         WidgetsFullSheet sheet = (WidgetsFullSheet) launcher.getLayoutInflater()
>                 .inflate(R.layout.widgets_full_sheet, launcher.getDragLayer(), false);
>         sheet.mIsOpen = false;
>         launcher.getDragLayer().addView(sheet);
>         sheet.open(animate);
>         return sheet;
>     }
> ```
> 
> screen shots:
> ![Screenshot_1572579913](https://user-images.githubusercontent.com/23213530/68001019-55fe6d00-fc88-11e9-89ac-702b14d1be86.png)
> 
> ![Screenshot_1572579945](https://user-images.githubusercontent.com/23213530/68001040-6282c580-fc88-11e9-9307-dedd9efbc3d2.png)
