### ISSUE TITLE
Feature question: Possible to move back button to the other side?

### ISSUE THREAD

**Issue by zocker-160** [amirzaidi/Shade#34]
I don't know if that is something a launcher is even possible to influence, but would it be possible to move the back button to the other (right) side?

Right now it is on the left side and I am used to have it on the other side like Samsung has it.

Thank you for this awesome launcher!

**Comment by amirzaidi** [comment]
Sorry but that's not (easily) achievable by the launcher. You could use some kind of floating overlay app from the Play Store if you want this functionality.
