### ISSUE TITLE
App icons become black

### ISSUE THREAD

**Issue by rehans** [amirzaidi/Shade#35]
Hey,

I have just updated to the latest version two hours ago and all over sudden some app icons look like in the picture.

![shade_launcher_bug](https://user-images.githubusercontent.com/4066879/83977713-f8f42500-a902-11ea-93b8-36a3dcf9ccf3.jpg)

Any idea?

**Comment by rehans** [comment]
I just tried fo figure out what goes wrong. I had put the icon shape to circle. After putting it back to the default shape, at least all icons show up correctly again.

But at the moment the cirlce shape option causes icons to get black on my device.

**Comment by amirzaidi** [comment]
Should be fixed in the new release, change the icon shape once to reset the icon cache

**Comment by rehans** [comment]
> Should be fixed in the new release, change the icon shape once to reset the icon cache

It is fixed. Thanks!
