### ISSUE TITLE
Custom icon shapes

### ISSUE THREAD

**Issue by kleinph** [amirzaidi/Shade#36]
Some apps have custom icon shapes, most prominent example being the F-Droid store. But regardless which shape options is chosen the icons are forced into predefined shapes, even with the default shape setting.
![F-Droid Shade launcher](https://user-images.githubusercontent.com/566413/84564769-b26c5380-ad64-11ea-9567-106bda60dbb8.png)
Other launcher apps like the port of LineageOS Trebuchet are capable of properly displaying the custom shape:
![F-Droid Trebuchet](https://user-images.githubusercontent.com/566413/84564772-b8facb00-ad64-11ea-8799-40fd93654c20.png)
So is it possible to implement this feature?

**Comment by amirzaidi** [comment]
The top is working as intended by Google, I probably won't change the behaviour.
