### ISSUE TITLE
BUG: bottom of the screen is clickable and opens homescreen

### ISSUE THREAD

**Issue by aljinovic** [amirzaidi/Shade#44]
When in any app, tap on the bottom edge of the screen acts as if you tapped the home button. This is especially annoying when keyboard is open because a tap just below the space key opens the homescreen.

Reproducible on Xiaomi A1 Android 9.0 (hardware home|recents|back buttons) and Nexus 5x Android 8.1 (software buttons, no gestures).

**Comment by aljinovic** [comment]
bump

**Comment by amirzaidi** [comment]
Disable the home button accessibility service.
