### ISSUE TITLE
Build error in Android Studio and gradle CLI

### ISSUE THREAD

**Issue by alanorth** [amirzaidi/Shade#52]
I'm getting the following error while trying to build Shade in both Android Studio and gradle on the command line:

```console
A problem occurred configuring root project 'Shade'.
> Could not create task ':processAospWithoutQuickstepDebugManifest'.
   > org.gradle.api.file.ProjectLayout.directoryProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/DirectoryProperty;
```

What is the correct way to build Shade? Thanks!

**Comment by amirzaidi** [comment]
I use gradle wrapper with gradle-5.4.1, I've heard other versions give weird errors, so check which gradle version is used in your gradle wrapper. Also do not click the "Update Gradle version" when prompted as that breaks the build script as well.

The build variant you need to build is shadeCustomUiDebug (or shadeCustomUiRelease from the Generate Signed APK window). Currently you're building aospWithoutQuickstep, which should still work, but will build almost clean AOSP and not Shade.

The right Gradle build target might be assemble and not process, but I'm not sure as I've only ever built from within Android Studio.

**Comment by alanorth** [comment]
Thanks @amirzaidi. I got that error just opening Android Studio so I didn't even get far enough to choose a build! I don't know how to use a gradle wrapper without a `gradlew` script in the root (usually provided in the source). How are you doing it?

**Comment by amirzaidi** [comment]
You need ./gradle/wrapper/gradle-wrapper.jar and ./gradle/wrapper/gradle-wrapper.properties

Usually Android Studio gives you the option to generate these

**Comment by alanorth** [comment]
@amirzaidi I see in the Gradle docs that you can use the following command to [generate the wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper):

```console
$ gradle wrapper
```

One issue is that I was originally on the `q` branch and it doesn't work there. I switched to the `p` branch and it works there, so now I can do `./gradlew`. For what it's worth, the Gradle docs suggest checking the wrapper files into version control so this is easier for other developers.

I was able to produce an APK with this command:

```
$ ./gradlew clean assembleShade
```

**Comment by amirzaidi** [comment]
> For what it's worth, the Gradle docs suggest checking the wrapper files into version control so this is easier for other developers.

Yeah I probably should do that, the only reason I don't is because Google excludes it by default from their Launcher3 repo.

**Comment by alanorth** [comment]
> Google excludes it by default from their Launcher3 repo.

Ah! I see... yes I understand the rationale behind wanting to stay as close to upstream as possible. It's up to you! Thanks for everything.
