### ISSUE TITLE
Get back hidden apps

### ISSUE THREAD

**Issue by Knud3** [amirzaidi/Shade#65]
I might be blind (please guide me if thats the case), but as launcher have option to hide apps then how to get back those hidden apps?

**Comment by nogweii** [comment]
See also https://github.com/amirzaidi/Shade/issues/40 but the way to see hidden apps is to scroll down the list of apps in the app drawer, then **keep scrolling in a continuous motion, long past what you think is the bottom**. The app drawer will 'snap' and the list of apps will be replaced with the hidden ones.

**Comment by kahidna** [comment]
Looking at this stuff also.
This issue deserves to be closed.

cc @Knud3
